version: '2'

services:
  udp-packet-forwarder:
    image: rakwireless/udp-packet-forwarder:latest
    depends_on:
      - helium-miner
    restart: always
    privileged: true
    volumes:
      - pktfwdr:/var/pktfwd
    devices:
      - /dev/spidev0.0
      - /dev/ttyAMA0
    environment:
      - MODEL="RAK2245"
    
  helium-miner:
    build: ./helium-gateway
    privileged: true
    expose:
      - "1680"
      - "44158"
    ports:
      - "44158:44158/tcp"
    volumes:
      - miner-storage:/var/data
      - miner-log:/var/log/miner
      - pktfwdr:/var/pktfwd
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/i2c-1:/dev/i2c-1
    restart: on-failure
    labels:
      io.balena.features.balena-api: '1'

volumes:
  miner-storage:
  miner-log:
  pktfwdr: